// Level grids are 24 x 14 tiles of 40px = 960 x 560.
//
// Legend
//   #  solid wall          =  one-way platform      .  empty
//   P  Lamput spawn        E  escape hatch          o  goo orb
//   1  Skinny Doc          2  Fat Doc               H  morph prop
//   ~  sticky goo (solid, slows you)                ^  zap-net hazard
//   C  conveyor right      c  conveyor left
//
//   Morph pads (touch one to take that form — you can only hold ONE):
//   A  ANVIL  heavy: hold DOWN in the air to smash through cracked floor
//   S  SPRING high jump
//   B  BLIMP  hold JUMP while falling to glide; rides updrafts
//   K  KEY    opens a locked gate, then it is spent
//   H  PROP   the disguise: stand on it and morph, docs walk past
//
//   X  cracked floor (only ANVIL breaks it)     G  locked gate (only KEY)
//   U  updraft (only BLIMP rides it)
//   -  horizontal lift     |  vertical lift         L  laser emitter

export const TILE = 40;
export const COLS = 24;
export const ROWS = 14;

export const FORMS = {
  heavy:  { label: "ANVIL",  tint: "#8A8FA8", hint: "DOWN in the air to smash" },
  spring: { label: "SPRING", tint: "#E0B23C", hint: "jumps far higher" },
  float:  { label: "BLIMP",  tint: "#7FBFE0", hint: "hold JUMP to glide" },
  key:    { label: "KEY",    tint: "#E0C04C", hint: "opens one gate" },
  decoy:  { label: "PROP",   tint: "#6FAE6B", hint: "SHIFT on a prop to hide" },
};
export const PAD_FORM = { A: "heavy", S: "spring", B: "float", K: "key" };

export const LEVELS = [
  {
    name: "Wake Up, Goo",
    hint: "Grab every goo orb, then reach the hatch. Tap jump twice to blob-bounce!",
    unlock: "BLOB-BOUNCE  ·  double jump unlocked",
    par: 35, vision: 190, docSpeed: 0.78,
    grid: [
      "########################",
      "#......................#",
      "#.........o............#",
      "#......======..........#",
      "#......................#",
      "#..====.........====...#",
      "#......................#",
      "#..o.............o.....#",
      "#.====.........=====...#",
      "#......................#",
      "#......................#",
      "#......................#",
      "#.P........1..........E#",
      "########################",
    ],
  },
  {
    name: "Hide and Sneak",
    hint: "Stand on a potted prop and press SHIFT to morph. Docs walk right past you.",
    unlock: "MORPH  ·  disguise yourself on props",
    par: 45, vision: 230, docSpeed: 0.9,
    grid: [
      "########################",
      "#......................#",
      "#....o.........o.......#",
      "#...=====....=======...#",
      "#......................#",
      "#......................#",
      "#.........o............#",
      "#.....==========.......#",
      "#......................#",
      "#..o...................#",
      "#.=====................#",
      "#......................#",
      "#.P.....H..1...H......E#",
      "########################",
    ],
  },
  {
    name: "Dead Weight",
    hint: "Touch the anvil pad to go heavy, then hold DOWN in mid-air to smash through.",
    unlock: "ANVIL  ·  heavy enough to break the floor",
    par: 50, vision: 230, docSpeed: 0.85,
    grid: [
      "########################",
      "#......................#",
      "#....o.......A....o....#",
      "#..=====...=====...====#",
      "#......................#",
      "#......................#",
      "#....XXXX......XXXX....#",
      "#....####......####....#",
      "#......................#",
      "#..o......2.........o..#",
      "#.====....====......===#",
      "#......................#",
      "#.P.......1...........E#",
      "########################",
    ],
  },
  {
    name: "Bounce",
    hint: "Stand on a spring pad and jump straight up \u2014 the ledge is directly overhead.",
    unlock: "SPRING  ·  reach what you could not",
    par: 55, vision: 240, docSpeed: 0.9,
    grid: [
      "########################",
      "#..o.............o.....#",
      "#.====..........=====..#",
      "#......................#",
      "#......................#",
      "#........2.oH..........#",
      "#.......=======........#",
      "#......................#",
      "#..S.............S.....#",
      "#..====.........=====..#",
      "#......................#",
      "#......................#",
      "#.P.......1.H.........E#",
      "########################",
    ],
  },
  {
    name: "Updraft",
    hint: "Take the blimp, hold JUMP as you fall, and let the vents carry you.",
    unlock: "BLIMP  ·  glide, and ride the vents",
    par: 65, vision: 250, docSpeed: 0.95,
    grid: [
      "########################",
      "#..o....U.......U...o..#",
      "#.===...U.......U..====#",
      "#.......U.......U......#",
      "#.......U.......U......#",
      "#....o..U.......U..o...#",
      "#..====.U.......U.====.#",
      "#.......U.......U......#",
      "#.......U.......U......#",
      "#....B..U.......U......#",
      "#..=====U.......U===...#",
      "#.......U.......U......#",
      "#.P...1.U.......U....2E#",
      "########################",
    ],
  },
  {
    name: "Locked Ward",
    hint: "One key, one gate. Work out which side you need to be on first.",
    unlock: "KEY  ·  one gate, one chance",
    par: 70, vision: 250, docSpeed: 1.0,
    grid: [
      "########################",
      "#....o.......G....o....#",
      "#..=====.....G..=====..#",
      "#............G.........#",
      "#......K.....G.........#",
      "#..=======...G...====..#",
      "#............G.........#",
      "#..o.........G......o..#",
      "#.====.......G....====.#",
      "#............G.........#",
      "#............G.........#",
      "#............G.........#",
      "#.P...H.1....G....H.2.E#",
      "########################",
    ],
  },
  {
    name: "Double Trouble",
    hint: "Fat Doc joined the shift. He is slow, but his eyes are wide.",
    unlock: "FAT DOC  ·  slower, but sees wider",
    par: 55, vision: 250, docSpeed: 0.95,
    grid: [
      "########################",
      "#.o.................o..#",
      "#.=====.........=====..#",
      "#..........o...........#",
      "#.......========.......#",
      "#......................#",
      "#......................#",
      "#..=====.......=====...#",
      "#......................#",
      "#.........o............#",
      "#.....==========.......#",
      "#......................#",
      "#.P....H.1..H....2....E#",
      "########################",
    ],
  },
  {
    name: "Goo Dash",
    hint: "Press X to dash through the air. Zap-nets sting — do not land on them.",
    unlock: "GOO DASH  ·  press X for a burst of speed",
    par: 60, vision: 250, docSpeed: 1.0,
    grid: [
      "########################",
      "#......................#",
      "#...o..........o.......#",
      "#..=====......=====....#",
      "#......................#",
      "#......................#",
      "#....========.=======..#",
      "#......................#",
      "#.o..................o.#",
      "#====...............===#",
      "#..........o...........#",
      "#.........===..........#",
      "#.P.....1^^^^^^...2...E#",
      "########################",
    ],
  },
  {
    name: "Rise and Shine",
    hint: "Lifts move on their own. Ride them — and remember docs can ride too.",
    unlock: "LIFTS  ·  moving platforms in the ward",
    par: 70, vision: 260, docSpeed: 1.0,
    grid: [
      "########################",
      "#....o............o....#",
      "#...====........====...#",
      "#.........o............#",
      "#.........|............#",
      "#......................#",
      "#..-...........-.......#",
      "#......................#",
      "#.o.................o..#",
      "#=====........=======..#",
      "#......................#",
      "#......................#",
      "#.P....H1...H...2.....E#",
      "########################",
    ],
  },
  {
    name: "Sticky Situation",
    hint: "Green sludge slows everything that stands on it. Use it to lose a chase.",
    unlock: "WALL CLING  ·  hug a wall to slide and leap",
    par: 75, vision: 270, docSpeed: 1.05,
    grid: [
      "########################",
      "#..o..............o....#",
      "#.=====.........=====..#",
      "#..........o...........#",
      "#......................#",
      "#...~~~~~~~..~~~~~~~...#",
      "#.........====.........#",
      "#.o..................o.#",
      "#====..^^^^^^....=====.#",
      "#......................#",
      "#......................#",
      "#......................#",
      "#.P....H.1..H..~~~~.2.E#",
      "########################",
    ],
  },
  {
    name: "Laser Ward",
    hint: "Beams blink on and off. Time your run — or morph and wait it out.",
    unlock: "LASERS  ·  blinking security beams",
    par: 85, vision: 200, docSpeed: 0.82,
    grid: [
      "########################",
      "#.......L......L.......#",
      "#......................#",
      "#......................#",
      "#......................#",
      "#......................#",
      "#......................#",
      "#......................#",
      "#..o................o..#",
      "#.=====..........====..#",
      "#..........o...........#",
      "#.........====...o.....#",
      "#.P...H......1....H...E#",
      "########################",
    ],
  },
  {
    name: "Conveyor Chaos",
    hint: "Belts drag you sideways. Fight the current or let it fling you.",
    unlock: "CONVEYORS  ·  the floor has opinions",
    par: 90, vision: 285, docSpeed: 1.12,
    grid: [
      "########################",
      "#..o............o......#",
      "#.CCCCC.......ccccc....#",
      "#......................#",
      "#......................#",
      "#...=====...=====......#",
      "#......................#",
      "#.o.................o..#",
      "#ccccc.........CCCCCC..#",
      "#......................#",
      "#........o...o.........#",
      "#...........===........#",
      "#.P.....1H^^^^H...2...E#",
      "########################",
    ],
  },
  {
    name: "Lights Out",
    hint: "The ward goes dark. Docs carry torches — stay out of the cones.",
    unlock: "BLACKOUT  ·  you glow, they search",
    par: 95, dark: true, vision: 300, docSpeed: 1.12,
    grid: [
      "########################",
      "#..o..............o....#",
      "#.====..........=====..#",
      "#......................#",
      "#......................#",
      "#...=======..=======...#",
      "#......................#",
      "#.o.................o..#",
      "#====.....===.....=====#",
      "#......................#",
      "#.....o.......o........#",
      "#......................#",
      "#.P.....H....1.H.2..H.E#",
      "########################",
    ],
  },
  {
    name: "The Specimen Lab",
    hint: "Everything at once, and three docs on the payroll. Get out, Lamput.",
    unlock: "FINAL SHIFT  ·  everything, all at once",
    par: 120, vision: 300, docSpeed: 1.2,
    grid: [
      "########################",
      "#..o....L.....L....o...#",
      "#.====...........====..#",
      "#......................#",
      "#.........|............#",
      "#..=====.......=====...#",
      "#........o.............#",
      "#.o...CCCCCCC.......o..#",
      "#====...........-..====#",
      "#......................#",
      "#......o.....o.........#",
      "#.....===..............#",
      "#.P...H^^^.1.2H^^^..1.E#",
      "########################",
    ],
  },
  {
    name: "The Goo-Vac 5000",
    hint: "They built a machine. Dodge the hose, then hit the core while it cools.",
    unlock: "BOSS FIGHT  ·  wreck the extractor",
    par: 150, vision: 280, docSpeed: 1.2, boss: true,
    grid: [
      "########################",
      "#......................#",
      "#......................#",
      "#......................#",
      "#......................#",
      "#..====..........====..#",
      "#......................#",
      "#......................#",
      "#....====......====....#",
      "#......................#",
      "#......................#",
      "#......................#",
      "#.P..H.........H......E#",
      "########################",
    ],
  },
];

export const SOLID = new Set(["#", "~", "C", "c", "X", "G"]);
export const ONEWAY = new Set(["="]);

export function isSolid(ch) { return SOLID.has(ch); }
export function isOneWay(ch) { return ONEWAY.has(ch); }
